name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio:${{github.run_number}} .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio .

      - name: Image scan trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/portfolio:${{github.run_number}}
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Push image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:${{github.run_number}}
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # port: ${{ secrets.PORT }}
          script: |
            docker rm -f resume
            docker run -d --name resume -p 8080:5001 ${{ secrets.DOCKER_USERNAME }}/portfolio:${{github.run_number}}
